'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { FormField } from '@/components/ui/form-field';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { createOperationLog, createPayable, createTitleTransaction, recordBillingPayment } from '@/lib/actions/fdm-operations';

type LogRow = { operation_log_id: string; occurred_at: string; module: string; action: string; description: string; client?: { full_name: string } | null };
type TitleRow = { title_transaction_id: string; title_number: string | null; status: string; current_agency: string | null; started_on: string; target_completion_on: string | null; last_follow_up_on: string | null; client?: { client_id: string; full_name: string } | null; property?: { property_id: string; location: string; block_number: number; lot_number: number } | null; requirements?: { status: string }[] };
type ClientChoice = { client_id: string; full_name: string };
type LotChoice = { property_id: string; location: string; block_number: number; lot_number: number };
type ContractRow = { contract_id: string; contract_number: string; contract_type: string; status: string; signed_on: string | null; client?: { full_name: string } | null };
type BillingAccount = { account_id: string; total_contract_price: number; remaining_balance: number; status: string; property?: { location: string; block_number: number; lot_number: number } | null; parties?: { is_primary: boolean; client?: { full_name: string } | null }[] };
type Payable = { payable_id: string; payee_name: string; category: string; description: string; amount: number; due_on: string | null; status: string };

const peso = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' });

export function OperationsLogSection({ logs }: { logs: LogRow[] }) {
  const router = useRouter();
  const [module, setModule] = useState<'Client' | 'Contract' | 'Title transfer' | 'Billing' | 'Payable' | 'Document' | 'Other'>('Client');
  const [action, setAction] = useState('');
  const [description, setDescription] = useState('');
  const [saving, setSaving] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); try { await createOperationLog({ module, action, description }); toast.success('Activity recorded.'); setAction(''); setDescription(''); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not record activity.'); } finally { setSaving(false); } }
  return <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Record activity</CardTitle><CardDescription>Keep the next staff member informed without relying on a paper logbook.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label>Module</Label><Select value={module} onValueChange={(value) => setModule(value as typeof module)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['Client','Contract','Title transfer','Billing','Payable','Document','Other'].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><FormField id="operation-action" label="Action" value={action} onChange={(e) => setAction(e.target.value)} placeholder="Called client" required /><div className="space-y-2"><Label htmlFor="operation-description">Details</Label><textarea id="operation-description" value={description} onChange={(e) => setDescription(e.target.value)} required className="min-h-28 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="What happened, what is needed next, and who should follow up?" /></div><Button className="w-full" disabled={saving}>{saving ? 'Saving…' : 'Add to operations log'}</Button></form></CardContent></Card><Card variant="section"><CardHeader><CardTitle>Recent activity</CardTitle><CardDescription>Latest 100 cross-department records.</CardDescription></CardHeader><CardContent className="space-y-3 overflow-y-auto">{logs.length === 0 ? <Empty message="No activity has been recorded yet." /> : logs.map((log) => <div key={log.operation_log_id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-foreground">{log.action}</p><span className="text-xs text-muted-foreground">{new Date(log.occurred_at).toLocaleString('en-PH')}</span></div><p className="mt-1 text-sm text-muted-foreground">{log.description}</p><p className="mt-2 text-xs font-medium text-accent-blue-foreground">{log.module}{log.client ? ` · ${log.client.full_name}` : ''}</p></div>)}</CardContent></Card></div>;
}

export function LegalWorkspaceSection({ titles, clients, lots, contracts }: { titles: TitleRow[]; clients: ClientChoice[]; lots: LotChoice[]; contracts: ContractRow[] }) {
  const router = useRouter(); const [clientId, setClientId] = useState(''); const [propertyId, setPropertyId] = useState(''); const [titleNumber, setTitleNumber] = useState(''); const [target, setTarget] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); try { await createTitleTransaction({ clientId, propertyId, titleNumber, targetCompletionOn: target }); toast.success('Title-transfer checklist created.'); setClientId(''); setPropertyId(''); setTitleNumber(''); setTarget(''); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not start title transfer.'); } finally { setSaving(false); } }
  return <div className="space-y-6"><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Start title transfer</CardTitle><CardDescription>Creates an FDM checklist for BIR, LGU/Assessor, and Registry of Deeds requirements.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><ChoiceSelect label="Client" value={clientId} onChange={setClientId} choices={clients.map(x=>[x.client_id,x.full_name])} /><ChoiceSelect label="Property lot" value={propertyId} onChange={setPropertyId} choices={lots.map(x=>[x.property_id,`${x.location} · Block ${x.block_number}, Lot ${x.lot_number}`])} /><FormField id="title-number" label="Current title number" value={titleNumber} onChange={e=>setTitleNumber(e.target.value)} placeholder="Optional / to verify" /><FormField id="target-date" type="date" label="Target completion" value={target} onChange={e=>setTarget(e.target.value)} /><Button className="w-full" disabled={!clientId || !propertyId || saving}>{saving ? 'Creating…' : 'Create checklist'}</Button></form></CardContent></Card><Card variant="section"><CardHeader><CardTitle>Title transfer queue</CardTitle><CardDescription>Items with missing documents must be verified by legal staff before agency submission.</CardDescription></CardHeader><CardContent className="grid gap-3 overflow-y-auto md:grid-cols-2">{titles.length === 0 ? <Empty message="No title transfers have been started." /> : titles.map(title => { const complete=(title.requirements??[]).filter(r=>r.status==='Verified'||r.status==='Not applicable').length; const total=title.requirements?.length??0; return <div key={title.title_transaction_id} className="rounded-lg border border-border p-4"><p className="font-semibold">{title.client?.full_name ?? 'Client'} · {title.property ? `B${title.property.block_number} L${title.property.lot_number}` : 'Property'}</p><p className="mt-1 text-sm text-muted-foreground">{title.status}{title.current_agency ? ` · ${title.current_agency}` : ''}</p><div className="mt-3 flex items-center justify-between text-xs"><span>{complete}/{total} requirements verified</span><span className="text-muted-foreground">Target: {title.target_completion_on ?? 'Not set'}</span></div></div>})}</CardContent></Card></div><Card><CardHeader><CardTitle>Contracts on file</CardTitle><CardDescription>Contract records will be the source for terms, parties, and uploaded agreement copies.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{contracts.length===0?<Empty message="No contracts recorded yet."/>:contracts.map(contract=><div key={contract.contract_id} className="rounded-lg border border-border p-3"><p className="font-medium">{contract.contract_number}</p><p className="text-sm text-muted-foreground">{contract.client?.full_name ?? 'Client'} · {contract.contract_type}</p><p className="mt-2 text-xs text-accent-blue-foreground">{contract.status}</p></div>)}</CardContent></Card></div>;
}

export function BillingWorkspaceSection({ accounts }: { accounts: BillingAccount[] }) {
  const router=useRouter(); const [accountId,setAccountId]=useState(''); const [amount,setAmount]=useState(''); const [method,setMethod]=useState('Cash'); const [reference,setReference]=useState(''); const [saving,setSaving]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{await recordBillingPayment({accountId,amount:Number(amount),paymentMethod:method,referenceNumber:reference});toast.success('Payment recorded and ledger balance updated.');setAmount('');setReference('');router.refresh();}catch(error){toast.error(error instanceof Error?error.message:'Could not record payment.');}finally{setSaving(false);}}
  return <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Record client payment</CardTitle><CardDescription>Payments reduce the current ledger balance. Corrections must be reviewed, not overwritten.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><ChoiceSelect label="Ledger account" value={accountId} onChange={setAccountId} choices={accounts.map(a=>[a.account_id,`${a.parties?.find(p=>p.is_primary)?.client?.full_name ?? 'Client'} · ${a.property ? `B${a.property.block_number} L${a.property.lot_number}`:''}`])}/><FormField id="payment-amount" type="number" min="0.01" step="0.01" label="Amount received" value={amount} onChange={e=>setAmount(e.target.value)} required /><ChoiceSelect label="Payment method" value={method} onChange={setMethod} choices={['Cash','Bank deposit','Bank transfer','Cheque','Online payment'].map(x=>[x,x])}/><FormField id="payment-reference" label="Receipt / reference no." value={reference} onChange={e=>setReference(e.target.value)} placeholder="Optional but recommended"/><Button className="w-full" disabled={!accountId||!amount||saving}>{saving?'Recording…':'Record payment'}</Button></form></CardContent></Card><Card variant="section"><CardHeader><CardTitle>Billing accounts</CardTitle><CardDescription>Balances are live after each recorded payment.</CardDescription></CardHeader><CardContent className="space-y-3 overflow-y-auto">{accounts.length===0?<Empty message="No active ledger accounts found."/>:accounts.map(a=>{const client=a.parties?.find(p=>p.is_primary)?.client?.full_name??'Client';return <div key={a.account_id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold">{client}</p><span className="text-xs text-accent-blue-foreground">{a.status}</span></div><p className="text-sm text-muted-foreground">{a.property?.location} · Block {a.property?.block_number}, Lot {a.property?.lot_number}</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><span>Total: <strong>{peso.format(Number(a.total_contract_price))}</strong></span><span>Balance: <strong>{peso.format(Number(a.remaining_balance))}</strong></span></div></div>})}</CardContent></Card></div>;
}

export function PayablesSection({ payables }: { payables: Payable[] }) {
 const router=useRouter();const [payeeName,setPayeeName]=useState('');const [category,setCategory]=useState('Title processing');const [description,setDescription]=useState('');const [amount,setAmount]=useState('');const [dueOn,setDueOn]=useState('');const [saving,setSaving]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{await createPayable({payeeName,category,description,amount:Number(amount),dueOn});toast.success('Payable sent for review.');setPayeeName('');setDescription('');setAmount('');setDueOn('');router.refresh();}catch(error){toast.error(error instanceof Error?error.message:'Could not create payable.');}finally{setSaving(false);}}
 return <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Record payable</CardTitle><CardDescription>Use this for title-processing, courier, document, and other operating costs. New entries start “For review”.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><FormField id="payee" label="Payee / agency" value={payeeName} onChange={e=>setPayeeName(e.target.value)} placeholder="e.g. Registry of Deeds" required/><FormField id="payable-category" label="Category" value={category} onChange={e=>setCategory(e.target.value)} /><FormField id="payable-description" label="Description" value={description} onChange={e=>setDescription(e.target.value)} required/><FormField id="payable-amount" type="number" min="0" step="0.01" label="Amount" value={amount} onChange={e=>setAmount(e.target.value)} required/><FormField id="payable-due" type="date" label="Due date" value={dueOn} onChange={e=>setDueOn(e.target.value)}/><Button className="w-full" disabled={saving}>{saving?'Saving…':'Send for review'}</Button></form></CardContent></Card><Card variant="section"><CardHeader><CardTitle>Payables queue</CardTitle><CardDescription>Approval ownership can be assigned once FDM confirms its finance policy.</CardDescription></CardHeader><CardContent className="space-y-3 overflow-y-auto">{payables.length===0?<Empty message="No payables have been recorded."/>:payables.map(p=><div key={p.payable_id} className="rounded-lg border border-border p-4"><div className="flex justify-between gap-2"><p className="font-semibold">{p.payee_name}</p><span className="text-xs text-accent-blue-foreground">{p.status}</span></div><p className="mt-1 text-sm text-muted-foreground">{p.description}</p><div className="mt-3 flex justify-between text-sm"><strong>{peso.format(Number(p.amount))}</strong><span className="text-muted-foreground">Due: {p.due_on??'Not set'}</span></div></div>)}</CardContent></Card></div>;
}

function ChoiceSelect({label,value,onChange,choices}:{label:string;value:string;onChange:(value:string)=>void;choices:string[][]}){return <div className="space-y-2"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={`Select ${label.toLowerCase()}`}/></SelectTrigger><SelectContent>{choices.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>}
function Empty({message}:{message:string}){return <p className="rounded-lg border border-dashed border-border p-6 text-center text-sm text-muted-foreground">{message}</p>}
